import logging

from rest_framework.views import exception_handler


logger = logging.getLogger(__name__)

def core_exception_handler(exc, context):
    # If an exception is thrown that we don't explicitly handle here, we want
    # to delegate to the default exception handler offered by DRF. If we do
    # handle this exception type, we will still want access to the response
    # generated by DRF, so we get that response up front.
    response = exception_handler(exc, context)
    
    # Now add the HTTP status code to the response.

    return response