# Generated by Django 4.2.3 on 2023-07-12 12:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='webp_image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
