# Generated by Django 4.2.3 on 2023-07-12 12:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_webp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='webp_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
