name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "DEBUG=True" >> .env
        echo "ALLOWED_HOSTS=test" >> .env
        echo "ALLOWED_HOSTS=*" >> .env
        echo "CORS_ALLOWED_ORIGINS=http://localhost,http://127.0.0.1" >> .env
        echo "SECRET_KEY=test" >> .env

    - name: Run Tests
      run: |
        python manage.py test
